# Script to check for Air and install it if not present, then run it
# Air is a live-reload tool for Go applications

# Function to load .env file into environment
function Load-EnvFile {
    param (
        [string]$EnvFilePath
    )
    
    if (Test-Path $EnvFilePath) {
        Write-Host "Loading environment variables from .env file..." -ForegroundColor Cyan
        Get-Content $EnvFilePath | ForEach-Object {
            $line = $_.Trim()
            # Skip empty lines and comments
            if ($line -and -not $line.StartsWith("#")) {
                $parts = $line -split "=", 2
                if ($parts.Count -eq 2) {
                    $key = $parts[0].Trim()
                    $value = $parts[1].Trim()
                    # Remove quotes if present
                    $value = $value -replace '^["'']|["'']$', ''
                    [Environment]::SetEnvironmentVariable($key, $value, "Process")
                    Write-Host "  Set $key" -ForegroundColor Gray
                }
            }
        }
        Write-Host "Environment variables loaded successfully!" -ForegroundColor Green
        Write-Host ""
    }
}

# Function to create default .env file
function Create-DefaultEnvFile {
    param (
        [string]$EnvFilePath
    )
    
    Write-Host "Creating default .env file..." -ForegroundColor Yellow
    
    $defaultEnv = @"
# StarX API Environment Configuration
# This file is automatically generated and gitignored
# Update these values according to your local development setup

# Required: Google Cloud Configuration
GOOGLE_APPLICATION_CREDENTIALS=path/to/your/service-account-key.json
GOOGLE_PROJECT_ID=your-project-id

# Required: Datastore Configuration
DATASTORE_NAME=your-datastore-name

# Required: Pub/Sub Configuration
PUBSUB_TOPIC=your-pubsub-topic
PUBSUB_SUBSCRIPTION=your-pubsub-subscription

# Required: Frontend Configuration
FRONTEND_ENDPOINT=http://localhost:3000

# Optional: Queue Configuration (defaults to 'pubsub')
QUEUE_TYPE=pubsub

# Optional: OAuth Configuration
OAUTH_CLIENT_ID=

# Optional: Firebase Configuration
FIREBASE_API_KEY=
FIREBASE_AUTH_DOMAIN=
FIREBASE_DEV_BEARER_TOKEN=

# Optional: Steam API
STEAM_API_KEY=

# Optional: Server Security Keys
SERVER_KEY=
SERVER_AUTH_CA_CURRENT=
SERVER_AUTH_CA_PREVIOUS=
"@
    
    Set-Content -Path $EnvFilePath -Value $defaultEnv -Encoding UTF8
    Write-Host "Created .env file at: $EnvFilePath" -ForegroundColor Green
    Write-Host ""
    Write-Host "IMPORTANT: Please update the .env file with your actual configuration values!" -ForegroundColor Yellow
    Write-Host "Required fields:" -ForegroundColor Yellow
    Write-Host "  - GOOGLE_APPLICATION_CREDENTIALS or GOOGLE_PROJECT_ID" -ForegroundColor Yellow
    Write-Host "  - DATASTORE_NAME" -ForegroundColor Yellow
    Write-Host "  - PUBSUB_TOPIC" -ForegroundColor Yellow
    Write-Host "  - PUBSUB_SUBSCRIPTION" -ForegroundColor Yellow
    Write-Host "  - FRONTEND_ENDPOINT" -ForegroundColor Yellow
    Write-Host ""
    
    # Ask user if they want to edit the file now
    $response = Read-Host "Would you like to edit the .env file now? (y/n)"
    if ($response -eq "y" -or $response -eq "Y") {
        if (Get-Command notepad -ErrorAction SilentlyContinue) {
            Start-Process notepad $EnvFilePath -Wait
        } else {
            Write-Host "Please edit $EnvFilePath manually" -ForegroundColor Yellow
        }
    }
    
    Write-Host ""
}

# Check for .env file
$envFilePath = Join-Path (Join-Path $PSScriptRoot "..") ".env"
if (-not (Test-Path $envFilePath)) {
    Create-DefaultEnvFile -EnvFilePath $envFilePath
    Write-Host "Press any key to continue after updating .env file..." -ForegroundColor Cyan
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    Write-Host ""
} else {
    Write-Host "Found .env file - Air will load environment variables automatically" -ForegroundColor Green
    Write-Host ""
}

Write-Host "Checking for Air installation..." -ForegroundColor Cyan

# Check if Air is installed
$airInstalled = $false
try {
    $airVersion = & air -v 2>&1
    if ($LASTEXITCODE -eq 0) {
        $airInstalled = $true
        Write-Host "Air is already installed: $airVersion" -ForegroundColor Green
    }
} catch {
    $airInstalled = $false
}

# Install Air if not present
if (-not $airInstalled) {
    Write-Host "Air not found. Installing Air..." -ForegroundColor Yellow
    
    # Check if Go is installed
    try {
        $goVersion = & go version
        Write-Host "Go is installed: $goVersion" -ForegroundColor Green
    } catch {
        Write-Host "ERROR: Go is not installed. Please install Go first." -ForegroundColor Red
        Write-Host "Download from: https://go.dev/dl/" -ForegroundColor Yellow
        exit 1
    }
    
    # Install Air using go install
    Write-Host "Running: go install github.com/air-verse/air@latest" -ForegroundColor Cyan
    & go install github.com/air-verse/air@latest
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Air installed successfully!" -ForegroundColor Green
        
        # Verify installation
        try {
            $airVersion = & air -v 2>&1
            Write-Host "Installed version: $airVersion" -ForegroundColor Green
        } catch {
            Write-Host "WARNING: Air was installed but may not be in PATH." -ForegroundColor Yellow
            Write-Host "Make sure $(go env GOPATH)\bin is in your PATH." -ForegroundColor Yellow
        }
    } else {
        Write-Host "ERROR: Failed to install Air." -ForegroundColor Red
        exit 1
    }
}

# Check if .air.toml exists
if (-not (Test-Path ".air.toml")) {
    Write-Host "WARNING: .air.toml not found in current directory." -ForegroundColor Yellow
    Write-Host "Air will use default configuration." -ForegroundColor Yellow
}

# Check for templ installation
Write-Host ""
Write-Host "Checking for Templ installation..." -ForegroundColor Cyan
$templInstalled = $false
try {
    $templVersion = & templ version 2>&1
    if ($LASTEXITCODE -eq 0) {
        $templInstalled = $true
        Write-Host "Templ is already installed: $templVersion" -ForegroundColor Green
    }
} catch {
    $templInstalled = $false
}

if (-not $templInstalled) {
    Write-Host "Templ is not installed. Installing..." -ForegroundColor Yellow
    Write-Host "Running: go install github.com/a-h/templ/cmd/templ@latest" -ForegroundColor Gray
    
    & go install github.com/a-h/templ/cmd/templ@latest
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Templ installed successfully!" -ForegroundColor Green
        
        # Verify installation
        try {
            $templVersion = & templ version 2>&1
            Write-Host "Installed version: $templVersion" -ForegroundColor Green
        } catch {
            Write-Host "WARNING: Templ was installed but may not be in PATH." -ForegroundColor Yellow
            Write-Host "Make sure $(go env GOPATH)\bin is in your PATH." -ForegroundColor Yellow
        }
    } else {
        Write-Host "ERROR: Failed to install Templ." -ForegroundColor Red
        exit 1
    }
}

Write-Host ""
Write-Host "Setup complete!" -ForegroundColor Green
